services:
  medicore-app:
    image: medicore-app:latest
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    secrets:
      - db_password

secrets:
  db_password:
    file: ./db_password.txt
